### ISSUE TITLE
Rename Developer(s) to Main author(s) or so

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsxsd#20]
Distinction between **Developer**s and **Contributor**s is very vague -- what is it a developer?

I suggest either renaming **Developer**s to **Main author**s, or adding even slightly more granularity via generic **Person**s with **Role**s (then should perhaps merge with **Contact**s and their **Role**s)

**Comment by joncison** [comment]
Done !

**Comment by matuskalas** [comment]
What version?

Another alternative to **Main author**s could be **Creator**s.

**Comment by joncison** [comment]
I made the change to the README.md:
https://github.com/bio-tools/biotoolsxsd

did you mean something else ?
