### ISSUE TITLE
Reassignation of tools

### ISSUE THREAD

**Issue by samuelDemarest** [bio-tools/biotoolsxsd#22]
Can you reassign the rights of "Orphanet portal for rare diseases and orphan drugs" and "Orphanet Rare Disease Ontology" to the user "Inserm US14" (the common user of Orphanet)

Thank you

**Comment by joncison** [comment]
Wrong tracker, please use:
https://github.com/bio-tools/biotoolsregistry

Thanks

**Comment by ekry** [comment]
This is done now. "Orphanet portal for rare diseases and orphan drugs" and "Orphanet Rare Disease Ontology" now belong to Inserm US14.
