### ISSUE TITLE
We need persistent unique IDs also for individual operations and input and output parameters

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsxsd#28]
And perhaps also interfaces (of tools) and format options (of an input or output)

**Comment by matuskalas** [comment]
In addition to "data|operation|_etc._ handles"

They'll likely be very necessary in _workbench enabling_, workflows registering, and CWL integration

**Comment by matuskalas** [comment]
This is an issue of both https://github.com/bio-tools/biotoolsxsd and https://github.com/bio-tools/biotoolsregistry, so copied also there (See https://github.com/bio-tools/biotoolsregistry/issues/102).

**Comment by joncison** [comment]
We're a (very) long way from needing or being able to support this in bio.tools.
