### ISSUE TITLE
Registration of services

### ISSUE THREAD

**Issue by germa** [bio-tools/biotoolsxsd#40]
Is it possible to register services, e.g. "conversion and upload service" or "biostatistics consultation service" in bio.tools?

**Comment by joncison** [comment]
This is more an issue for https://github.com/bio-tools/biotoolsregistry/issues/new or you can mail registry-support@elixir-dk.org.

Anyhow, bio.tools scope is limited to application software, which includes online services (Web applications, APIs etc.) but not what might be described as consultancy / paid-for work done by others.

Cheers!
