### ISSUE TITLE
Input/Output duplicate attributes from dataType

### ISSUE THREAD

**Issue by redmitry** [bio-tools/biotoolsxsd#44]
Input and Output elements are defined as a restriction of dataType

dataType type already has "data" and "format" elements defined.
What is the reason to duplicate them in Input/Output (with the same definitions).

**Comment by joncison** [comment]
If memory serves, this is because they have different comments (via <xs:annotation>).  I *thought* the restriction was necessary in order to do this (I could be mistaken)

**Comment by redmitry** [comment]
I see... Really don't know how to do this without redefining elements :-( .
